### ISSUE TITLE
Metalbond release github action needs an update after ironcore migration

### ISSUE THREAD

**Issue by guvenc** [ironcore-dev/metalbond#87]
Metalbond release github action needs an update after ironcore migration.
The release github action needs to be tested and adjusted as it has external dependencies. (like gitlab)

CC: @afritzler @Vincinator

**Comment by afritzler** [comment]
Uhm I think the release is handled via the GH actions in this project already: https://github.com/ironcore-dev/metalbond/blob/master/.github/workflows/release.yml#L5

Once the new version is released there also should be release artefacts (`.deb`) files added to the release notes in the release section.

Can you elaborate a bit more on the gitlab dependency as I don't see anything in this project here?

**Comment by guvenc** [comment]
I just tried (new version released) and release artifacts are created successfully. That part seems to be fine.
The complete "release" of metalbond consists of the changes on the gitlab side as well. That is why I wanted to track it here.
(otherwise it is kind of broken as we dont directly use the deb packages)
If you guys can tell/assure that the gitlab side can cope with the new URL with ironcore-dev in the name then this issue is already handled and can be closed.

**Comment by afritzler** [comment]
Oh is this related to some Gardenlinux repo stuff?

**Comment by guvenc** [comment]
Yes, @Vincinator took care of that part but the deb packages were being added to Gardenlinux repo. Yes, that is my understanding.

**Comment by Vincinator** [comment]
The current integration is just a workaround. 
The GitLab Pipeline will be deprecated and replaced with a GitHub actions based CI/CD pipeline early 2024.

Until then, I can take care of integrating metalbond with the old workaround.

I will get back to you when we have the new CI/CD pipeline available, so we can find a good way how to integrate metalbond into GL repos.

**Comment by Vincinator** [comment]
metalbond `0.3.5` is in gardenlinux `today` dist now. Let me know if you need this version in Garden Linux 1312 repo as well.

**Comment by guvenc** [comment]
Thank you Vincent. `today` dist is sufficient.
